"""
Constants for the licensing module.

This module contains all constants used across the licensing app:
- Plan IDs
- Rule IDs
- Enums
"""

from enum import Enum


class BillingPeriod(str, Enum):
    """
    Billing period for subscriptions.

    Values match the license_price_period parametric entity IDs.
    """
    MONTHLY = "MONTHLY"
    YEARLY = "YEARLY"


# License Application IDs
DEFAULT_APPLICATION = "DEFAULT"

# License Price Period IDs
MONTHLY_PERIOD = BillingPeriod.MONTHLY.value
YEARLY_PERIOD = BillingPeriod.YEARLY.value

# License Currency IDs (ISO 4217, uppercase)
EUR_CURRENCY = "EUR"

# Default currency used when none is specified
DEFAULT_CURRENCY = EUR_CURRENCY

# License Plan IDs
FREE_PLAN = "FREE"
STARTER_PLAN = "STARTER"
PRO_PLAN = "PRO"

# License Rule IDs
MAX_USERS = "MAX_USERS"
MAX_PROJECTS_PER_MONTH = "MAX_PROJECTS_PER_MONTH"

# Role IDs
LICENSE_ADMIN_ROLE = "LICENSE_ADMIN_ROLE"

# Error messages
AUTHENTICATION_REQUIRED_ERROR = "AUTHENTICATION_REQUIRED_ERROR"
NOT_CLIENT_ASSOCIATED_USER_ERROR = "NOT_CLIENT_ASSOCIATED_USER_ERROR"
NO_PAYMENT_CUSTOMER_ERROR = "NO_PAYMENT_CUSTOMER_ERROR"
CHECKOUT_SESSION_FAILED_ERROR = "CHECKOUT_SESSION_FAILED_ERROR"
NO_ACTIVE_SUBSCRIPTION_ERROR = "NO_ACTIVE_SUBSCRIPTION_ERROR"
SAME_PLAN_ERROR = "SAME_PLAN_ERROR"
PLAN_NOT_FOUND_ERROR = "PLAN_NOT_FOUND_ERROR"
PLAN_NOT_PRICED_ERROR = "PLAN_NOT_PRICED_ERROR"
CANCEL_SUBSCRIPTION_FAILED_ERROR = "CANCEL_SUBSCRIPTION_FAILED_ERROR"
NO_PROVIDER_SUBSCRIPTION_ERROR = "NO_PROVIDER_SUBSCRIPTION_ERROR"