"""
Constants for the licensing module.

This module contains all constants used across the licensing app:
- Plan IDs
- Rule IDs
- Enums
"""

from enum import Enum


class BillingPeriod(str, Enum):
    """
    Billing period for subscriptions.

    Values match the license_price_period parametric entity IDs.
    """
    MONTHLY = "MONTHLY"
    YEARLY = "YEARLY"


# License Application IDs
DEFAULT_APPLICATION = "DEFAULT"

# License Price Period IDs
MONTHLY_PERIOD = BillingPeriod.MONTHLY.value
YEARLY_PERIOD = BillingPeriod.YEARLY.value

# License Commitment IDs
NO_COMMITMENT = "NO_COMMITMENT"

# License Billing Mode IDs
MANUAL_BILLING = "MANUAL"
PROVIDER_BILLING = "PROVIDER"

# License Discount Unit IDs
PERCENT_UNIT = "PERCENT"

# License Discount Grant IDs
MANUAL_GRANT = "MANUAL"

# License Currency IDs (ISO 4217, uppercase)
EUR_CURRENCY = "EUR"

# Default currency used when none is specified
DEFAULT_CURRENCY = EUR_CURRENCY

# License Plan IDs
FREE_PLAN = "FREE"
STARTER_PLAN = "STARTER"
PRO_PLAN = "PRO"

# License Rule IDs
MAX_USERS = "MAX_USERS"

# Role IDs
LICENSE_ADMIN_ROLE = "LICENSE_ADMIN_ROLE"

# Error messages
AUTHENTICATION_REQUIRED_ERROR = "AUTHENTICATION_REQUIRED_ERROR"
NOT_CLIENT_ASSOCIATED_USER_ERROR = "NOT_CLIENT_ASSOCIATED_USER_ERROR"
NO_PAYMENT_CUSTOMER_ERROR = "NO_PAYMENT_CUSTOMER_ERROR"
CHECKOUT_SESSION_FAILED_ERROR = "CHECKOUT_SESSION_FAILED_ERROR"
NO_ACTIVE_SUBSCRIPTION_ERROR = "NO_ACTIVE_SUBSCRIPTION_ERROR"
SAME_PLAN_ERROR = "SAME_PLAN_ERROR"
PLAN_NOT_FOUND_ERROR = "PLAN_NOT_FOUND_ERROR"
PLAN_NOT_PRICED_ERROR = "PLAN_NOT_PRICED_ERROR"
BILLING_TERMS_CHANGE_ERROR = "BILLING_TERMS_CHANGE_ERROR"
NOTICE_PERIOD_EXPIRED_ERROR = "NOTICE_PERIOD_EXPIRED_ERROR"
PROVIDER_SUBSCRIPTION_ACTIVE_ERROR = "PROVIDER_SUBSCRIPTION_ACTIVE_ERROR"
CANCEL_SUBSCRIPTION_FAILED_ERROR = "CANCEL_SUBSCRIPTION_FAILED_ERROR"
NO_PROVIDER_SUBSCRIPTION_ERROR = "NO_PROVIDER_SUBSCRIPTION_ERROR"