"""
Integration tests for the atomic execution of GraphQL mutations.

The unit tests check the contract of run_atomic against a mocked savepoint.
These check what that contract is for, against a real database: the resolvers
generated by lys_creation, lys_edition and lys_delete run on a real SQLite
session wrapped in the ThreadSafeSessionProxy the DatabaseSessionExtension
uses, the request ends with the same final commit, and what survives is read
back from a fresh session.

The entities are declared on a dedicated declarative base so the tests do not
depend on the application registries.
"""
from types import SimpleNamespace
from typing import Optional

import pytest
import pytest_asyncio
import strawberry
from sqlalchemy import ForeignKey, String, event, select
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from strawberry import relay

from lys.core.errors import LysError
from lys.core.graphql.atomic import run_atomic
from lys.core.graphql.create import _creation_resolver_generator
from lys.core.graphql.delete import _delete_resolver_generator
from lys.core.graphql.edit import _edition_resolver_generator
from lys.core.graphql.extensions import ThreadSafeSessionProxy
from lys.core.graphql.fields import _is_root_mutation

OWNER = "owner-1"


class _Base(DeclarativeBase):
    pass


class _Project(_Base):
    """A row readable only by its owner, as an entity's check_permission decides."""

    __tablename__ = "atomic_project"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    name: Mapped[str] = mapped_column(String)
    owner_id: Mapped[str] = mapped_column(String)

    def check_permission(self, user_id: Optional[str], access_type) -> bool:
        return self.owner_id == user_id


class _Task(_Base):
    """A row referencing a project: deleting a referenced project violates the FK."""

    __tablename__ = "atomic_task"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    project_id: Mapped[str] = mapped_column(ForeignKey("atomic_project.id"))


class _ProjectService:
    entity_class = _Project

    @staticmethod
    async def get_by_id(object_id: str, session) -> Optional[_Project]:
        return await session.get(_Project, object_id)


class _ProjectNode:
    """The subset of an EntityNode the generated resolvers use."""

    app_manager = None
    entity_class = _Project
    service_class = _ProjectService

    @classmethod
    def from_obj(cls, obj):
        return obj


@pytest_asyncio.fixture
async def session_factory(tmp_path):
    engine = create_async_engine(f"sqlite+aiosqlite:///{tmp_path / 'atomic.db'}")

    @event.listens_for(engine.sync_engine, "connect")
    def _enable_foreign_keys(dbapi_connection, _):
        cursor = dbapi_connection.cursor()
        cursor.execute("PRAGMA foreign_keys=ON")
        cursor.close()

    async with engine.begin() as connection:
        await connection.run_sync(_Base.metadata.create_all)

    factory = async_sessionmaker(engine, expire_on_commit=False)
    async with factory() as session:
        session.add(_Project(id="p1", name="original", owner_id=OWNER))
        session.add(_Task(id="t1", project_id="p1"))
        await session.commit()

    yield factory

    await engine.dispose()


@pytest_asyncio.fixture
async def request_session(session_factory):
    """The request session, as the DatabaseSessionExtension opens and wraps it."""
    session = session_factory()
    yield ThreadSafeSessionProxy(session)
    await session.close()


def _info(session, user_id: Optional[str] = OWNER):
    return SimpleNamespace(context=SimpleNamespace(
        session=session,
        app_manager=None,
        connected_user={"sub": user_id} if user_id else None,
        access_type=None,
        webservice_name="atomic_test",
    ))


async def _end_request(session) -> None:
    """The extension's final commit: a resolver error never reaches it."""
    await session.commit()


async def _project_names(session_factory) -> list[str]:
    async with session_factory() as session:
        return sorted((await session.execute(select(_Project.name))).scalars())


async def _project(session_factory, project_id: str) -> Optional[_Project]:
    async with session_factory() as session:
        return await session.get(_Project, project_id)


class TestCreation:

    @pytest.mark.asyncio
    async def test_a_creation_that_fails_after_writing_leaves_nothing(self, request_session, session_factory):
        async def create_project(self, info):
            info.context.session.add(_Project(id="side", name="side row", owner_id=OWNER))
            await info.context.session.flush()
            raise LysError((400, "REFUSED"), "refused after a first write")

        resolver = _creation_resolver_generator(create_project, _ProjectNode)

        with pytest.raises(LysError):
            await resolver(None, info=_info(request_session))
        await _end_request(request_session)

        assert await _project_names(session_factory) == ["original"]

    @pytest.mark.asyncio
    async def test_a_creation_refused_by_the_access_check_is_not_saved(self, request_session, session_factory):
        async def create_project(self, info):
            return _Project(id="p2", name="someone else's", owner_id="owner-2")

        resolver = _creation_resolver_generator(create_project, _ProjectNode)

        with pytest.raises(LysError):
            await resolver(None, info=_info(request_session))
        await _end_request(request_session)

        assert await _project(session_factory, "p2") is None

    @pytest.mark.asyncio
    async def test_a_successful_creation_is_saved(self, request_session, session_factory):
        async def create_project(self, info):
            return _Project(id="p2", name="created", owner_id=OWNER)

        resolver = _creation_resolver_generator(create_project, _ProjectNode)

        created = await resolver(None, info=_info(request_session))
        await _end_request(request_session)

        assert created.id == "p2"
        assert await _project_names(session_factory) == ["created", "original"]


class TestEdition:

    @pytest.mark.asyncio
    async def test_an_edit_moving_the_object_out_of_reach_is_refused_and_undone(
            self, request_session, session_factory
    ):
        """Before the savepoint, the access check refused the edit and the final commit saved it."""
        async def hand_over(self, obj, info):
            obj.name = "handed over"
            obj.owner_id = "owner-2"

        resolver = _edition_resolver_generator(hand_over, _ProjectNode)

        with pytest.raises(LysError):
            await resolver(None, id=relay.GlobalID("ProjectNode", "p1"), info=_info(request_session))
        await _end_request(request_session)

        project = await _project(session_factory, "p1")
        assert (project.name, project.owner_id) == ("original", OWNER)

    @pytest.mark.asyncio
    async def test_an_edit_failing_after_a_flush_is_undone(self, request_session, session_factory):
        async def rename_then_fail(self, obj, info):
            obj.name = "renamed"
            await info.context.session.flush()
            raise LysError((400, "REFUSED"), "refused after flushing")

        resolver = _edition_resolver_generator(rename_then_fail, _ProjectNode)

        with pytest.raises(LysError):
            await resolver(None, id=relay.GlobalID("ProjectNode", "p1"), info=_info(request_session))
        await _end_request(request_session)

        assert (await _project(session_factory, "p1")).name == "original"


class TestDelete:

    @pytest.mark.asyncio
    async def test_deleting_a_referenced_row_fails_as_the_mutations_error(self, request_session, session_factory):
        """The FK violation surfaces in the resolver, not at the final commit after a reported success."""
        async def delete_project(self, obj, info):
            pass

        resolver = _delete_resolver_generator(delete_project, _ProjectNode)

        with pytest.raises(Exception, match="FOREIGN KEY"):
            await resolver(None, id=relay.GlobalID("ProjectNode", "p1"), info=_info(request_session))
        await _end_request(request_session)

        assert await _project(session_factory, "p1") is not None

    @pytest.mark.asyncio
    async def test_a_delete_whose_resolver_fails_leaves_its_writes_out(self, request_session, session_factory):
        async def detach_then_fail(self, obj, info):
            await info.context.session.delete(await info.context.session.get(_Task, "t1"))
            await info.context.session.flush()
            raise LysError((400, "REFUSED"), "refused after detaching")

        resolver = _delete_resolver_generator(detach_then_fail, _ProjectNode)

        with pytest.raises(LysError):
            await resolver(None, id=relay.GlobalID("ProjectNode", "p1"), info=_info(request_session))
        await _end_request(request_session)

        async with session_factory() as session:
            assert await session.get(_Task, "t1") is not None
        assert await _project(session_factory, "p1") is not None


class TestOperation:

    @pytest.mark.asyncio
    async def test_a_failing_mutation_does_not_undo_an_earlier_one(self, request_session, session_factory):
        """One savepoint per mutation: the first already reported success to the caller."""
        async def first():
            request_session.add(_Project(id="p2", name="first", owner_id=OWNER))
            await request_session.flush()

        async def second():
            request_session.add(_Project(id="p3", name="second", owner_id=OWNER))
            await request_session.flush()
            raise LysError((400, "REFUSED"), "second refused")

        await run_atomic(request_session, first)
        with pytest.raises(LysError):
            await run_atomic(request_session, second)
        await _end_request(request_session)

        assert await _project_names(session_factory) == ["first", "original"]

    @pytest.mark.asyncio
    async def test_a_write_committed_before_refusing_is_kept(self, request_session, session_factory):
        """Persist-then-refuse, as the login records a failed attempt."""
        async def record_then_refuse():
            request_session.add(_Project(id="attempt", name="attempt", owner_id=OWNER))
            await request_session.commit()
            raise LysError((400, "REFUSED"), "refused after committing")

        async def next_mutation():
            request_session.add(_Project(id="p2", name="next", owner_id=OWNER))
            await request_session.flush()

        with pytest.raises(LysError):
            await run_atomic(request_session, record_then_refuse)
        await run_atomic(request_session, next_mutation)
        await _end_request(request_session)

        assert await _project_names(session_factory) == ["attempt", "next", "original"]


class TestRootMutationDetection:
    """_is_root_mutation read against the Info a real Strawberry execution passes."""

    @pytest.mark.asyncio
    async def test_only_a_mutations_root_field_is_atomic(self):
        seen: dict[str, bool] = {}

        @strawberry.type
        class Payload:
            @strawberry.field
            def nested(self, info: strawberry.Info) -> bool:
                seen["nested"] = _is_root_mutation(info)
                return True

        @strawberry.type
        class Query:
            @strawberry.field
            def read(self, info: strawberry.Info) -> bool:
                seen["query"] = _is_root_mutation(info)
                return True

        @strawberry.type
        class Mutation:
            @strawberry.mutation
            def write(self, info: strawberry.Info) -> Payload:
                seen["mutation"] = _is_root_mutation(info)
                return Payload()

        schema = strawberry.Schema(query=Query, mutation=Mutation)

        assert (await schema.execute("mutation { write { nested } }")).errors is None
        assert (await schema.execute("query { read }")).errors is None

        assert seen == {"mutation": True, "nested": False, "query": False}
