WAITING_EMAILING_STATUS = 'WAITING'
SENT_EMAILING_STATUS = 'SENT'
ERROR_EMAILING_STATUS = 'ERROR'

FORGOTTEN_PASSWORD_EMAILING_TYPE = "FORGOTTEN_PASSWORD"
EMAIL_VALIDATION_EMAILING_TYPE = "EMAIL_VALIDATION"
UPDATE_EMAIL_WARNING_EMAILING_TYPE = "UPDATE_EMAIL_WARNING"
USER_WELCOME_EMAILING_TYPE = "USER_WELCOME"