EMPTY_LOGIN_ERROR = (400, "EMPTY_LOGIN_ERROR")
EMPTY_PASSWORD_ERROR = (400, "EMPTY_PASSWORD_ERROR")
ACCESS_DENIED_ERROR = (401, "ACCESS_DENIED_ERROR")
INVALID_REFRESH_TOKEN_ERROR = (401, "INVALID_REFRESH_TOKEN_ERROR")
WRONG_CREDENTIALS_ERROR = (401, "WRONG_CREDENTIALS_ERROR")
WRONG_REFRESH_TOKEN_ERROR = (401, "WRONG_REFRESH_TOKEN_ERROR")
BLOCKED_USER_ERROR = (403, "BLOCKED_USER_ERROR")
INVALID_XSRF_TOKEN_ERROR = (403, "INVALID_XSRF_TOKEN_ERROR")
ALREADY_CONNECTED_ERROR = (403, "ALREADY_CONNECTED_ERROR")


